# Generated by Django 4.0.6 on 2024-05-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('funding_goal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount_raised', models.DecimalField(decimal_places=2, default='0', max_digits=8)),
                ('number_of_investors', models.PositiveSmallIntegerField(default=0)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('owner', models.CharField(max_length=50)),
                ('is_sdg', models.BooleanField(default=False)),
                ('partner', models.CharField(max_length=200)),
                ('images_1', models.ImageField(blank=True, max_length=255, null=True, upload_to='home/project_images')),
                ('images_2', models.ImageField(blank=True, max_length=255, null=True, upload_to='home/project_images')),
                ('images_3', models.ImageField(blank=True, max_length=255, null=True, upload_to='home/project_images')),
                ('images_4', models.ImageField(blank=True, max_length=255, null=True, upload_to='home/project_images')),
                ('video', models.FileField(blank=True, max_length=255, null=True, upload_to='home/project_videos')),
                ('funding_type', models.IntegerField(choices=[(1, 'Equity'), (2, 'Debt'), (3, 'Donation'), (4, 'Reward')], default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='innovator',
            name='id',
        ),
        migrations.RemoveField(
            model_name='innovator',
            name='name',
        ),
        migrations.AddField(
            model_name='innovator',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='innovator',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='innovator',
            name='contact_number',
            field=models.BigIntegerField(default=123456789),
        ),
        migrations.AddField(
            model_name='innovator',
            name='date_of_birth',
            field=models.DateField(default=1012001),
        ),
        migrations.AddField(
            model_name='innovator',
            name='email',
            field=models.EmailField(default=0, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='innovator',
            name='first_name',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='innovator',
            name='last_name',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='innovator',
            name='no_of_projects',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='innovator',
            name='password',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='innovator',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='home/project_image/innovation_image'),
        ),
        migrations.AddField(
            model_name='innovator',
            name='project_list',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='innovator',
            name='username',
            field=models.CharField(default=0, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='innovator',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('first_name', models.CharField(default=0, max_length=50)),
                ('last_name', models.CharField(default=0, max_length=50)),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(upload_to='home/project_image/investor_image')),
                ('age', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField(default=1012001)),
                ('email', models.EmailField(default=0, max_length=254, unique=True)),
                ('contact_number', models.BigIntegerField(default=1112223333)),
                ('address', models.CharField(max_length=200)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('project_list', models.ManyToManyField(related_name='investors', to='home.project')),
            ],
        ),
    ]
