# Generated by Django 4.0.6 on 2024-05-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_project_remove_innovator_id_remove_innovator_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AddField(
            model_name='innovator',
            name='desc',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='innovator',
            name='education',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='innovator',
            name='interest',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='innovator',
            name='professional_history',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='owner_username',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.CharField(default=None, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='innovator',
            name='username',
            field=models.CharField(default=0, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='investor',
            name='username',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
