# Generated by Django 4.0.6 on 2024-05-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_project_id_innovator_desc_innovator_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovator',
            name='date_of_birth',
        ),
    ]
